### ISSUE TITLE
Could export UIBezierPath to SVG path?

### ISSUE THREAD

**Issue by arden** [shaps80/InkKit#2]
Could export UIBezierPath to SVG path?

**Comment by shaps80** [comment]
I have worked extensively lately with SVG in an app and I'm not 100% keen on writing in support for this LOL!

That said, I have considered this as its very useful. I'm currently looking into the new APIs for iOS 10 for how they are now dealing with renderer's for images and PDF, maybe something I can back port and add then even add iOS 10 support for SVG export.

If I did do this, I think I'd only include support for simple shapes and flat colours.

You're welcome to give it a shot and create a PR though ;)
