### ISSUE TITLE
Swift 3 Support

### ISSUE THREAD

**Issue by mainvolume-hq** [shaps80/InkKit#3]
Hi, 

Is there an updated version that compiles on x8 available? : )

**Comment by shaps80** [comment]
There is an open PR for Swift 3 support that compiles with Xcode 8. I do have some updates for that as well, as well as some new features.

However, I won't be merging this until Xcode 8 is released officially over the next few weeks.

**Comment by shaps80** [comment]
I'm closing this since https://github.com/shaps80/InkKit/issues/4 will address this issue
